version: "3.7"
services:
  postgres:
    build:
      context: Deployment/Docker/${APP}/Postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "54321:5432"
    # psql -U shop_root shop < /tmp/create_schema_init.sql
    # psql -U shop_root shop < /tmp/create_tables_init.sql
    # psql -U postgres -d shop
    volumes:
      - ./Deployment/DataBaseInit/Postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_role.sql:/docker-entrypoint-initdb.d/create_role_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_tables.sql:/tmp/create_tables_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_schema.sql:/tmp/create_schema_init.sql
      - ./Deployment/data/postgres-data:/var/lib/postgresql/data
  pgadmin:
    build:
      context: ./Deployment/Docker/${APP}/PgAdmin
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "test@mail.ru"
    #id = 172.17.0.1
    ports:
      - "16543:80"
    depends_on:
      - postgres

  postgresql_01:
    image: postgres
    container_name: postgresql_01
    restart: always
    volumes:
      - ./Deployment/data/postgresql_01:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

