version: "3.7"
services:
  postgres:
    build:
      context: Deployment/Docker/${APP}/Postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "54321:5432"
    # psql -U shop_root shop < /tmp/create_schema_init.sql
    # psql -U shop_root shop < /tmp/create_tables_init.sql
    # psql -U postgres -d shop
    volumes:
      - ./Deployment/DataBaseInit/Postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_role.sql:/docker-entrypoint-initdb.d/create_role_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_tables.sql:/tmp/create_tables_init.sql
      - ./Deployment/DataBaseInit/Postgres/create_schema.sql:/tmp/create_schema_init.sql
      - ./Deployment/data/postgres-data:/var/lib/postgresql/data
  pgadmin:
    build:
      context: ./Deployment/Docker/${APP}/PgAdmin
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "test@mail.ru"
    #id = 172.17.0.1
    ports:
      - "16543:80"
    depends_on:
      - postgres

  postgresql_01:
    image: postgres
    container_name: postgresql_01
    restart: always
    volumes:
      - ./Deployment/data/postgresql_01:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root


  # mysql -u root -p 12345 otus < /tmp/create_tables_init.sql
  # docker-compose exec otusdb bash
  # mysql --user=root --password=12345
  # LOAD DATA LOCAL INFILE '/tmp/Fashion.csv' INTO TABLE otus.fashion;
  # mysql --user=root --password=12345 shop < /tmp/world_db-195395-7d762d.sql
  otusdb:
    build:
      context: Deployment/Docker/${APP}/MySQL
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command:
      --init-file /init.sql
    volumes:
      - ./Deployment/data/otusdb:/var/lib/mysql
      - ./Deployment/DataBaseInit/MySQL/create_tables.sql:/tmp/create_tables_init.sql
      - ./Deployment/DataBaseInit/MySQL/world_db-195395-7d762d.sql:/tmp/world_db-195395-7d762d.sql
      - ./Deployment/DataBaseInit/MySQL/backup/backup_des.xbstream.gz-195395-386c6b.des3:/tmp/backup_des.xbstream.gz-195395-386c6b.des3
      - ./Deployment/DataBaseInit/csv/Fashion.csv:/tmp/Fashion.csv
      - ./Deployment/DataBaseInit/MySQL/init.sql:/init.sql
      - ./Deployment/Docker/Dev/MySQL/conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"

#  percona-server-mysql:
#    image: percona/percona-xtrabackup
#    container_name: percona-server
#    volumes:
#      - ./Deployment/DataBaseInit/MySQL/backup/backup_des.xbstream.gz-195395-386c6b.des3:/tmp/backups/backup_des.xbstream.gz-195395-386c6b.des3
#    environment:
#      MYSQL_ROOT_PASSWORD: 12345